### ISSUE TITLE
What are the requriments ? 依赖是什么？

### ISSUE THREAD

**Issue by tgzw1680** [LEXUGE/DHT-Spider#1]
比如bencode。还有什么需要安装的？谢谢

Translation:
Beside the `bencode`, any more requriments to install ? Thanks

**Comment by LEXUGE** [comment]
看错误提示吧，现在在Windows，不太方便回答

**Comment by LEXUGE** [comment]
抱歉，长时间忙碌，未回复。
近期会对项目做大量更新，会有更自动化的部署方案，在此不赘述，希望关注更新。

Translation:
I'll make some breaking changes recently. It can deploy more automaticly. So, watch the project.
